# Generated by Django 5.1.5 on 2025-02-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('blocking_user', 'Может заблокировать пользователя'), ('list_user', 'Может смотреть пользователей')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
