# Generated by Django 5.1.5 on 2025-02-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_manager', '0001_initial'),
        ('recipient_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_sending', models.DateField(blank=True, null=True, verbose_name='Дата первой отправки')),
                ('date_end_shipment', models.DateField(blank=True, null=True, verbose_name='Дата окончание отправки')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Create', 'Create'), ('Running', 'Running')], max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_manager.message', verbose_name='Сообщение')),
                ('recipient', models.ManyToManyField(to='recipient_manager.mailingrecipient')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateField(verbose_name='Дата и время попытки отправки')),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=20)),
                ('status_response', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
        ),
    ]
